### PR TITLE
Go wrapper for libtotalspaces2api.dylib

### PR DESCRIPTION
**Pull request by joedevivo**
This is going to be tricky, because this won't work until it can count on `github.com/binaryage/totalspaces2-api/go/totalspaces2` actually existing, which means it will all work once it's merged. That being said, here's what you can do...

When you have Go installed, `go get github.com/joedevivo/totalspaces2-api/go/totalspaces2`, but then copy the files it pulls down to `$GOPATH/src/github.com/binaryage/totalspaces2-api`, then the files will be where they need to be locally.

Then you can run `go install github.com/joedevivo/totalspaces2-api/go/totalspaces2-test` and you'll have a `$GOPATH/bin/totalspaces2-test` command that will validate the Go wrapper is working.

I'm not sure if the ruby ffi library needs the install_name for the `dylib` set, but if it doesn't, setting that one to 

```
install_name_tool -id "@executable_path/../src/github.com/binaryage/totalspaces2-api/go/totalspaces2/libtotalspaces2api.dylib" totalspaces2/libtotalspaces2api.dylib
```

Would allow the Go client to use the copy of the dylib, making a second copy unnecessary.

### CODE REVIEW

**Comment by joedevivo** [comment]
If you have trouble getting it working, don't hesitate to reach out.

**Comment by dabrady** [comment]
This is great! I just found the `totalspaces2-api/ruby` today, and was starting to think about writing a Lua wrapper for easy scripting. I can't wait to get started now that I have a reference for porting the API.

Wonderful choice of language for the first port, by the way. May I ask what drove you to create this Go wrapper?

**Comment by joedevivo** [comment]
That's a long story. The short version is that I've been looking for a Tiling window manager for macOS for some time. Finally, the 4.0 release of [KWM](https://github.com/koekeishiya/kwm) got me most of the way there. The biggest problem with the solution there was that the commands to switch spaces actually froze the Dock, creating some weirdness. Since the key combos just triggered shell commands to switch the desktop, scripting TotalSpaces2 to do that instead would have been pretty straight forward with the Ruby library.

I had some more ideas about things I want to keep consistent between KWM and TotalSpaces2, so eventually I'll want a service to keep track of those states and be able to make some decisions based on info from both aps. Since I'm learning Go for work, I figured it's worth doing that in Go for my own education, so this port will come in pretty handy then.

**Comment by sdsykes** [comment]
Awesomeness. I will merge asap.

**Comment by joedevivo** [comment]
great! once it's merge, I'll test and make sure the relative paths for the dylib work the way I think they will.

**Comment by sdsykes** [comment]
Sorry took a while, but merged we are.

**Pull request merged**
